### ISSUE TITLE
Make timestamps human readable

### ISSUE THREAD

**Issue by jkemp101** [closeio/tasktiger-admin#14]
The Task Detail page shows unix times that are difficult to use when troubleshooting issues.

* Task detail `time_last_queued`
* Task executions
   * `time_failed`
   * `time_started` 

We should format the fields in the task JSON blob as well as in each execution's JSON blob and render them as an HTML table. UNIX timestamps should be converted into human-readable times,  e.g. 

```
|--------------------------------------------------------------------|
| Time Last Queued | March 23, 2020 19:30:02.534 (1584991802.534387) |
|--------------------------------------------------------------------|
```

Fields that are lists (like `retry_on`) or more complicated fields (like `retry_method`) can be left as is, unless there is a quick way to format them nicely.

**Comment by froxCZ** [comment]
@thomasst 

Started working on this, so far I have:
![Screenshot 2021-04-08 at 12 26 13](https://user-images.githubusercontent.com/3979716/114011565-a73f6280-9865-11eb-9f24-247a409cda9d.png)


There are still many ways how to format it, so some hints would help.
1. I think the top block is fine. I would still keep the full json blob - in case more attributes are added on the task_dump that don't have UI yet. Or should put all the attributes as table rows dynamically?
2. Not sure if it is better to render executions as vertical or horizontal table. Also would like to add a full dump, but there is not much space left.
3. So far I have put the formatting logic into the render function in views.py. I have looked how queue detail does it (for `task.ts`), and there the float -> datetime conversion is done in tasktiger itself https://github.com/closeio/tasktiger/blob/d1d05095cd46f34cde21840f2e1e17c6262c9b91/tasktiger/task.py#L479. Another option would be to modify and reuse https://github.com/closeio/tasktiger-admin/blob/5f95e974f59c95d645b956d1bcd1eb2e945efb23/tasktiger_admin/integrations.py#L8 Not sure if worth it. Let me know

**Comment by thomasst** [comment]
> 1\. I think the top block is fine. I would still keep the full json blob - in case more attributes are added on the task_dump that don't have UI yet. Or should put all the attributes as table rows dynamically?

How about a simple inline-JavaScript toggle so we don't show it by default?


> 2\. Not sure if it is better to render executions as vertical or horizontal table. Also would like to add a full dump, but there is not much space left.

Yeah that looks weird, maybe each of the executions should be rendered as its own table in a similar way to the table at the top?

> 3\. So far I have put the formatting logic into the render function in views.py.

Ideally, this would be handled by the template in Jinja, e.g. `{{ created_at.strftime("%Y-%m-%d %H:%M:%S") }}`. You just want to make sure to pass a datetime object to the template.

**Comment by froxCZ** [comment]
Cool, will try that 👍 

3. Ah, I meant float -> datetime conversion but wrote formatting instead. Will send a PR next week where we can discuss the details.

**Comment by thomasst** [comment]
> 1. Will send a PR next week where we can discuss the details.

Sounds good! A PR will definitely help to discuss the details.

If you think something needs to be implemented in the `tasktiger` module itself, you can also submit a PR there. Ideally, the `tasktiger-admin` package should be using TaskTiger APIs and shouldn't have to make conversions from float to datetime.
