### ISSUE TITLE
python 3 compatibility 

### ISSUE THREAD

**Issue by mrname** [closeio/tasktiger-admin#8]
Given the recent EOL of python 2, this application should be updated to support python 3. This is now increasingly important because issues are popping up around tasktiger itself in regards to compatibility with 2.X, such as:

https://github.com/closeio/tasktiger/issues/140

**Comment by AlecRosenbaum** [comment]
I'll plan on working on this after handling https://github.com/closeio/tasktiger-admin/issues/9

**Comment by mrname** [comment]
Awesome, thanks @AlecRosenbaum let me know if you need any help.

**Comment by AlecRosenbaum** [comment]
This will go out with the next release.

I intend to do some more internal testing, then to release a new version shortly after.
